# Generated by Django 4.2.5 on 2023-11-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='crate_date',
            new_name='create_date',
        ),
    ]
