# Generated by Django 5.0 on 2023-12-10 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_crate_date_board_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='content',
        ),
        migrations.RemoveField(
            model_name='board',
            name='create_date',
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='board',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='shop/images/'),
        ),
        migrations.AddField(
            model_name='board',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
